package com.example.data

import android.content.Context
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import android.text.Layout
import android.text.StaticLayout
import android.text.TextPaint
import java.io.File
import java.io.FileOutputStream

object PdfGenerator {
    fun generatePdfForBook(context: Context, book: Book): File {
        val pdfFile = File(context.filesDir, "book_${book.id}.pdf")
        if (pdfFile.exists() && pdfFile.length() > 1000) {
            return pdfFile
        }

        val pdfDocument = PdfDocument()
        var pageNumber = 1

        val pageWidth = 595 // A4 Width in PostScript points (1/72 inch)
        val pageHeight = 842 // A4 Height
        val margin = 54 // 0.75 inch margin

        val contentWidth = pageWidth - (margin * 2)
        val contentHeight = pageHeight - (margin * 2)

        // Text Paints
        val titlePaint = TextPaint().apply {
            color = Color.BLACK
            textSize = 24f
            typeface = Typeface.create(Typeface.SERIF, Typeface.BOLD)
            isAntiAlias = true
        }

        val subtitlePaint = TextPaint().apply {
            color = Color.DKGRAY
            textSize = 14f
            typeface = Typeface.create(Typeface.SERIF, Typeface.ITALIC)
            isAntiAlias = true
        }

        val headingPaint = TextPaint().apply {
            color = Color.BLACK
            textSize = 18f
            typeface = Typeface.create(Typeface.SERIF, Typeface.BOLD)
            isAntiAlias = true
        }

        val bodyPaint = TextPaint().apply {
            color = Color.rgb(33, 33, 33)
            textSize = 12f
            typeface = Typeface.create(Typeface.SERIF, Typeface.NORMAL)
            isAntiAlias = true
        }

        val footerPaint = TextPaint().apply {
            color = Color.GRAY
            textSize = 10f
            typeface = Typeface.create(Typeface.SANS_SERIF, Typeface.NORMAL)
            isAntiAlias = true
        }

        // --- PAGE 1: COVER PAGE ---
        val coverPageInfo = PdfDocument.PageInfo.Builder(pageWidth, pageHeight, pageNumber++).create()
        val coverPage = pdfDocument.startPage(coverPageInfo)
        val coverCanvas = coverPage.canvas

        // Clean border
        val borderPaint = Paint().apply {
            color = Color.rgb(44, 62, 80)
            style = Paint.Style.STROKE
            strokeWidth = 3f
        }
        coverCanvas.drawRect(
            margin.toFloat() - 10f,
            margin.toFloat() - 10f,
            pageWidth.toFloat() - margin + 10f,
            pageHeight.toFloat() - margin + 10f,
            borderPaint
        )

        // Draw Cover details
        var currentY = pageHeight / 3f

        // Wrap Title
        val titleLayout = StaticLayout.Builder.obtain(book.title, 0, book.title.length, titlePaint, contentWidth)
            .setAlignment(Layout.Alignment.ALIGN_CENTER)
            .build()
        coverCanvas.save()
        coverCanvas.translate(margin.toFloat(), currentY)
        titleLayout.draw(coverCanvas)
        coverCanvas.restore()

        currentY += titleLayout.height + 20f

        // Wrap Author
        val authorText = "By ${book.author}"
        val authorLayout = StaticLayout.Builder.obtain(authorText, 0, authorText.length, subtitlePaint, contentWidth)
            .setAlignment(Layout.Alignment.ALIGN_CENTER)
            .build()
        coverCanvas.save()
        coverCanvas.translate(margin.toFloat(), currentY)
        authorLayout.draw(coverCanvas)
        coverCanvas.restore()

        currentY += authorLayout.height + 80f

        // Genre & Info
        val infoText = "Genre: ${book.genre}\n\nGenerated by Oceanic PDF Engine\nFor Offline Mobile Reading"
        val infoLayout = StaticLayout.Builder.obtain(infoText, 0, infoText.length, footerPaint, contentWidth)
            .setAlignment(Layout.Alignment.ALIGN_CENTER)
            .build()
        coverCanvas.save()
        coverCanvas.translate(margin.toFloat(), currentY)
        infoLayout.draw(coverCanvas)
        coverCanvas.restore()

        pdfDocument.finishPage(coverPage)

        // --- CHAPTERS PAGES ---
        val chapters = book.getChapters()
        for (chapter in chapters) {
            // We start a new page for each chapter
            var chapterPageInfo = PdfDocument.PageInfo.Builder(pageWidth, pageHeight, pageNumber++).create()
            var chapterPage = pdfDocument.startPage(chapterPageInfo)
            var canvas = chapterPage.canvas

            // Page header
            canvas.drawText(book.title.uppercase(), margin.toFloat(), margin.toFloat() - 15f, footerPaint)
            canvas.drawLine(
                margin.toFloat(),
                margin.toFloat() - 10f,
                pageWidth.toFloat() - margin,
                margin.toFloat() - 10f,
                footerPaint
            )

            // Chapter header on canvas
            val capTitle = chapter.title
            val capLayout = StaticLayout.Builder.obtain(capTitle, 0, capTitle.length, headingPaint, contentWidth)
                .setAlignment(Layout.Alignment.ALIGN_NORMAL)
                .build()

            canvas.save()
            canvas.translate(margin.toFloat(), margin.toFloat() + 15f)
            capLayout.draw(canvas)
            canvas.restore()

            var yOffset = margin.toFloat() + 15f + capLayout.height + 25f

            // Break the chapter content into paragraphs
            val paragraphs = chapter.content.split("\n\n").filter { it.isNotBlank() }
            for (paragraph in paragraphs) {
                val pText = paragraph.trim()
                val pLayout = StaticLayout.Builder.obtain(pText, 0, pText.length, bodyPaint, contentWidth)
                    .setAlignment(Layout.Alignment.ALIGN_NORMAL)
                    .setLineSpacing(4f, 1f)
                    .build()

                // Check if paragraph fits on the current page
                if (yOffset + pLayout.height > pageHeight - margin) {
                    // Draw footer with page number before closure
                    val pNumStr = "Page ${pageNumber - 1}"
                    canvas.drawText(
                        pNumStr,
                        pageWidth.toFloat() - margin - footerPaint.measureText(pNumStr),
                        pageHeight.toFloat() - margin + 20f,
                        footerPaint
                    )

                    pdfDocument.finishPage(chapterPage)

                    // Start new secondary page for this same chapter
                    chapterPageInfo = PdfDocument.PageInfo.Builder(pageWidth, pageHeight, pageNumber++).create()
                    chapterPage = pdfDocument.startPage(chapterPageInfo)
                    canvas = chapterPage.canvas

                    // Running headers
                    canvas.drawText(book.title.uppercase(), margin.toFloat(), margin.toFloat() - 15f, footerPaint)
                    canvas.drawLine(
                        margin.toFloat(),
                        margin.toFloat() - 10f,
                        pageWidth.toFloat() - margin,
                        margin.toFloat() - 10f,
                        footerPaint
                    )

                    yOffset = margin.toFloat() + 15f
                }

                // Draw paragraph layout onto page canvas
                canvas.save()
                canvas.translate(margin.toFloat(), yOffset)
                pLayout.draw(canvas)
                canvas.restore()

                yOffset += pLayout.height + 14f // Space between paragraphs
            }

            // Draw last page footer of the chapter before completion
            val pNumStr = "Page ${pageNumber - 1}"
            canvas.drawText(
                pNumStr,
                pageWidth.toFloat() - margin - footerPaint.measureText(pNumStr),
                pageHeight.toFloat() - margin + 20f,
                footerPaint
            )

            pdfDocument.finishPage(chapterPage)
        }

        // Save down to stream
        FileOutputStream(pdfFile).use { out ->
            pdfDocument.writeTo(out)
        }
        pdfDocument.close()

        return pdfFile
    }
}
